version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
install:
- cmd: nuget sources add -Name myget.graphql -Source https://www.myget.org/F/graphql-dotnet
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: pQ0rIQ8gurj473UPM5nIB81ML5Hhz63AxnqIXCDihWfUAXMqeWIKyMIqxs2a1Kaa
  skip_symbols: true
  artifact: /.*\.nupkg/